## Base class for every procedural level piece.
##
## A part stores only its parameters. All meshes and collision shapes are built
## at `_ready` into an unowned container, which means:
##   * the saved .tscn stays tiny and readable (just a transform + a few values),
##   * changing an export in the inspector reshapes the geometry live,
##   * geometry can never drift out of sync with the values that describe it.
##
## Subclasses override `_build()` and call `_box()`.
@tool
class_name MapPart
extends Node3D

## Children of this node are regenerated, never saved. Anything the level
## designer parents to the part (lights, props) keeps an owner and survives.
const GEOMETRY_NAME := "__generated"

var _geometry: Node3D
var _body: StaticBody3D
var _rebuild_queued := false


func _ready() -> void:
	rebuild()


## Rebuilds immediately. Prefer `queue_rebuild()` from property setters.
func rebuild() -> void:
	_clear_geometry()

	_geometry = Node3D.new()
	_geometry.name = GEOMETRY_NAME
	add_child(_geometry)

	_body = StaticBody3D.new()
	_body.name = "Collision"
	_body.collision_layer = Layers.WORLD
	_body.collision_mask = 0
	_geometry.add_child(_body)

	_build()

	if _body.get_child_count() == 0:
		_body.queue_free()


## Coalesces bursts of setter calls (dragging a spinbox) into one rebuild.
func queue_rebuild() -> void:
	if not is_node_ready() or _rebuild_queued:
		return
	_rebuild_queued = true
	_deferred_rebuild.call_deferred()


func _deferred_rebuild() -> void:
	_rebuild_queued = false
	rebuild()


func _clear_geometry() -> void:
	var stale: Array[Node] = []
	for child in get_children():
		# Unowned == generated by us. Designer-placed children always have an
		# owner because the editor sets it when they are added to the scene.
		if child.owner == null:
			stale.append(child)
	for child in stale:
		remove_child(child)
		child.queue_free()
	_geometry = null
	_body = null


## Override this. Called with `_geometry` and `_body` ready to receive children.
func _build() -> void:
	pass


# ------------------------------------------------------------------ helpers --

## Adds a textured box with matching collision. Sizes of zero are skipped so
## subclasses can emit degenerate segments without guarding every call.
func _box(
		center: Vector3,
		size: Vector3,
		surface: MapMaterials.Surface,
		uv_scale: float,
		collide: bool = true,
		rotation_deg: Vector3 = Vector3.ZERO) -> MeshInstance3D:
	if size.x <= 0.001 or size.y <= 0.001 or size.z <= 0.001:
		return null

	var mesh := BoxMesh.new()
	mesh.size = size

	var mi := MeshInstance3D.new()
	mi.mesh = mesh
	mi.position = center
	mi.rotation = rotation_deg * (PI / 180.0)
	mi.material_override = MapMaterials.get_material(surface, uv_scale)
	_geometry.add_child(mi)

	if collide:
		var shape := BoxShape3D.new()
		shape.size = size
		var cs := CollisionShape3D.new()
		cs.shape = shape
		cs.position = center
		cs.rotation = mi.rotation
		_body.add_child(cs)

	return mi


## Editor-only marker mesh, so gameplay-logic parts (spawn points, triggers)
## are visible while building but invisible in game.
func _editor_gizmo(size: Vector3, color: Color, offset: Vector3 = Vector3.ZERO) -> void:
	if not Engine.is_editor_hint():
		return
	var mesh := BoxMesh.new()
	mesh.size = size
	var mat := StandardMaterial3D.new()
	mat.albedo_color = color
	mat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	mat.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	mat.cull_mode = BaseMaterial3D.CULL_DISABLED
	var mi := MeshInstance3D.new()
	mi.mesh = mesh
	mi.position = offset
	mi.material_override = mat
	_geometry.add_child(mi)
